### ISSUE TITLE
config dataset query exception

### ISSUE THREAD

**Issue by tiborsimko** [vkuznet/dasgoclient#10]
Using older version of client from `/afs/cern.ch/user/v/valya/public/dasgoclient/dasgoclient_linux`, the following query works:

```console
$ ./dasgoclient_linux --query 'config dataset=/BuJpsiK_TuneZ2star_8TeV_Pythia6/Summer12-START53_V7C-v1/GEN-SIM' -json
```

Using self-compiled `master` branch latest bleeding edge version -- in order to have "byoutputdataset" in the config query output as introduced in #7 -- leads to the following exception:

```console
$ /usr/local/bin/dasgoclient --query 'config dataset=/BuJpsiK_TuneZ2star_8TeV_Pythia6/Summer12-START53_V7C-v1/GEN-SIM' -json
panic: interface conversion: interface {} is nil, not string

goroutine 1 [running]:
github.com/vkuznet/das2go/services.findReqMgrIds(0x86787d, 0x16, 0xc420076971, 0x40, 0x0, 0x0, 0x0, 0x0)
	/home/simko/go/src/github.com/vkuznet/das2go/services/reqmgr.go:155 +0x17d4
github.com/vkuznet/das2go/services.reqmgrConfigs(0x7ffda2c5edb8, 0x4f, 0xc420076960, 0x51, 0xc4204e6d40, 0x20, 0xc4204fe450, 0xc4204fa170, 0x1, 0x1, ...)
	/home/simko/go/src/github.com/vkuznet/das2go/services/reqmgr.go:206 +0x101
github.com/vkuznet/das2go/services.LocalAPIs.L_reqmgr2_configs(0x7ffda2c5edb8, 0x4f, 0xc420076960, 0x51, 0xc4204e6d40, 0x20, 0xc4204fe450, 0xc4204fa170, 0x1, 0x1, ...)
	/home/simko/go/src/github.com/vkuznet/das2go/services/reqmgr.go:193 +0x60
github.com/vkuznet/das2go/services.(*LocalAPIs).L_reqmgr2_configs(0xa5fe48, 0x7ffda2c5edb8, 0x4f, 0xc420076960, 0x51, 0xc4204e6d40, 0x20, 0xc4204fe450, 0xc4204fa170, 0x1, ...)
	<autogenerated>:20 +0x86
reflect.Value.call(0x8559c0, 0xa5fe48, 0x4e93, 0x860405, 0x4, 0xc4201bf498, 0x1, 0x1, 0xc420399740, 0x84ff00, ...)
	/usr/lib/go/src/reflect/value.go:434 +0x91f
reflect.Value.Call(0x8559c0, 0xa5fe48, 0x4e93, 0xc4201bf498, 0x1, 0x1, 0xa5fe48, 0x4e93, 0xc4201bf308)
	/usr/lib/go/src/reflect/value.go:302 +0xa4
main.processLocalApis(0x7ffda2c5edb8, 0x4f, 0xc420076960, 0x51, 0xc4204e6d40, 0x20, 0xc4204fe450, 0xc4204fa170, 0x1, 0x1, ...)
	/home/simko/private/project/opendata/cms-run2012/dasgoclient/main.go:553 +0x403
main.process(0x7ffda2c5edb8, 0x4f, 0x1, 0x85fff0, 0x1, 0x0)
	/home/simko/private/project/opendata/cms-run2012/dasgoclient/main.go:275 +0x2067
main.main()
	/home/simko/private/project/opendata/cms-run2012/dasgoclient/main.go:77 +0x466
```

@vkuznet Can you please have a look?

**Comment by vkuznet** [comment]
Tibor, thanks for reporting the bug. The fix is in https://github.com/vkuznet/das2go/commit/83e9837f192223d9c31f673961e466ba501e1bb0
you may try to recompile the code. Since the bug is fixed in dependency, you need to go to $GOROOT/src/github.com/vkuznet/das2go and pull out recent changes. Then you may recompile dasgoclient.

**Comment by vkuznet** [comment]
I have couple of more things to fix, then I'll submit new PR to merge changes into CVMFS.

**Comment by vkuznet** [comment]
Fix is already in CVMFS, closing the ticket.
