### ISSUE TITLE
Bug in site dataset=/a/b/c

### ISSUE THREAD

**Issue by vkuznet** [vkuznet/dasgoclient#11]
Here is failed query:
```
dasgoclient -query="site dataset=/MinimumBias1/Run2015E-v1/RAW"
panic: interface conversion: interface {} is nil, not string

goroutine 1 [running]:
github.com/vkuznet/das2go/services.LocalAPIs.L_combined_site4dataset(0xc420247650, 0x2c, 0x7fff5fbff2bd, 0x2a, 0xc42022fea0, 0x20, 0xc420247680, 0xc420237600, 0x1, 0x1, ...)
        /Users/vk/Work/Languages/Go/gopath/src/github.com/vkuznet/das2go/services/combined.go:141 +0x1103
github.com/vkuznet/das2go/services.(*LocalAPIs).L_combined_site4dataset(0x1620648, 0xc420247650, 0x2c, 0x7fff5fbff2bd, 0x2a, 0xc42022fea0, 0x20, 0xc420247680, 0xc420237600, 0x1, ...)
        <autogenerated>:4 +0x86
reflect.Value.call(0x14268a0, 0x1620648, 0x1a93, 0x143125b, 0x4, 0xc420127420, 0x1, 0x1, 0xc420327980, 0x1422000, ...)
        /usr/local/go/src/reflect/value.go:434 +0x91f
reflect.Value.Call(0x14268a0, 0x1620648, 0x1a93, 0xc420127420, 0x1, 0x1, 0x1620648, 0x1a93, 0xc420127290)
        /usr/local/go/src/reflect/value.go:302 +0xa4
main.processLocalApis(0xc420247650, 0x2c, 0x7fff5fbff2bd, 0x2a, 0xc42022fea0, 0x20, 0xc420247680, 0xc420237600, 0x1, 0x1, ...)
        /Users/vk/Work/Languages/Go/gopath/src/github.com/vkuznet/dasgoclient/main.go:590 +0x403
main.process(0x7fff5fbff2bd, 0x2a, 0x0, 0x1430e50, 0x1, 0x0, 0x0, 0x0)
        /Users/vk/Work/Languages/Go/gopath/src/github.com/vkuznet/dasgoclient/main.go:289 +0x2456
main.main()
        /Users/vk/Work/Languages/Go/gopath/src/github.com/vkuznet/dasgoclient/main.go:90 +0x69b
```

**Comment by vkuznet** [comment]
Fixed in this commit: https://github.com/vkuznet/das2go/commit/08d33886276836fa977d474b68d2abf2ba9da7ab

**Comment by vkuznet** [comment]
This query works fine now, closing the issue.
